app_version: 2025.4.4
capabilities:
- description: Homebridge is able to change file ownership.
  name: CHOWN
- description: Homebridge is able to change file ownership.
  name: FOWNER
- description: Homebridge is able to bypass file permissions.
  name: DAC_OVERRIDE
- description: Homebridge is able to bind to privileged ports.
  name: NET_BIND_SERVICE
- description: Homebridge is able to use raw sockets.
  name: NET_RAW
categories:
- productivity
changelog_url: https://github.com/homebridge/homebridge/releases
date_added: '2025-05-06'
description: Homebridge is a lightweight Node.js server you can run on your home network that emulates the iOS HomeKit API. It supports Plugins, which are community-contributed modules that provide a basic bridge from HomeKit to various 3rd-party APIs provided by manufacturers of "smart home" devices.
home: http://homebridge.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/homebridge/icons/icon.png
keywords:
- home-automation
- assistant
lib_version: 2.1.16
lib_version_hash: dac15686f882b9ce65b8549a3d5c0ed7bafe2df7a9028880d1a99b0ff4af1eff
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: homebridge
run_as_context:
- description: Homebridge runs as root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
screenshots:
- https://media.sys.truenas.net/apps/homebridge/screenshots/screenshot1.png
sources:
- https://github.com/homebridge/homebridge
title: Homebridge
train: community
version: 1.9.0
